#-------------------------------
# General Site Settings
url: "https://komikeros.com" # the base hostname & protocol for your site, e.g. http://example.com
s3_url: "https://dip7ok9f0gqax.cloudfront.net"


#-------------------------------
# Build Settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 12
paginate_path: "/latest/page/:num"


#-------------------------------
# Collections
collections:
  pages:
    output: true
    permalink: /:path
  posts:
    output: true
    permalink: /:slug
  authors:
    output: true
    permalink: /creators/:name

# Pages Path
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "comic"
      last: false
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      year_end: false
      ongoing: false
      feature: false
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"


sass:
  sass_dir: _sass
  style: compressed


exclude: ['extra', 'templates']