#-------------------------------
# Site Settings
title: Komikeros Library
description: A free public library for komiks.
logo: "/images/logo.svg"
logo_dark: "/images/logo-dark.svg"
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


#-------------------------------
# Navigation Settings
menu_settings:
  menu_items:
    - title: "Authors"
      url: "/authors/"
    - title: "Pages"
      submenu:
      - url: "/about/"
        title: "About"
      - url: "/contact/"
        title: "Contact"
      - url: "/featured/"
        title: "Featured"

# Call to action button
cta_button:
  enable: false
  cta_button_link: '/contact/'
  cta_button_text: Get in touch


#-------------------------------
# Hero Settings
hero:
  enable: true
  hero_title: Komikeros Library
  hero_description: A free public library for komiks.


#-------------------------------
# Tags Section Settings
tags_section:
  enable: true
  number_posts: 4 # To control how many posts to show under each tag section, set the value to a number. Three is the default.
  number_columns: 4 # You can specify the number of columns from 1-4 for large screen resolution. By default, the theme uses three columns grid.
  tags:
    - tag: "action"
    - tag: "comedy"
    - tag: "experimental"
    - tag: "fantasy"
    - tag: "historical"
    - tag: "horror"
    - tag: "romance"
    - tag: "sci-fi"
    - tag: "superhero"
    - tag: "classic"
    - tag: "indie"
    - tag: "preview"
    - tag: "queer"

# You can add many tag sections to the homepage; each section will show the recent posts by the tag.


#-------------------------------
# Authors Section Settings
authors_section:
  enable: true
  section_title: Creators


#-------------------------------
# Footer Settings
footer_description: A free public library for komiks.


# Social Links
social:
- {icon: "instagram", link: "https://instagram.com/komikerosph"}
- {icon: "twitter", link: "https://twitter.com/komikerosph"}

# Example of adding a new link to the footer - {icon: "instagram", link: "https://instagram.com"}
# Other icons can be found at https://ionicons.com/v4/


#-------------------------------
# Newsletter Settings
mailchimp_settings:
  enable: false
  mailchimp_title: Your title
  mailchimp_description: Your description
  mailchimp_identifier: Your form identifier
  mailchimp_input_text: Your email address
  mailchimp_button_text: Subscribe


#-------------------------------
# Contact Settings (Formspree)
contact:
  endpoint: xovaavza


#-------------------------------
# Comment Section (Disqus)
disqus_identifier: # Add your shortname for Disqus Comment.


#-------------------------------
# GoatCounter
goatcounter: komikeros